
# SEO settings
title: "I'm"
title2: "0x01" # default: ""
description: "All in One about Programming "
keywords: "0x01, TsaiYee, Yee, caiyi, 蔡一, Coding, Program, Life, Finance, Big Data, Machine Learn"
url: http://0x01.im # site url
baseurl: null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-88264578-1
repo: http://github.com/yeetsai
twitter_username: "yeesword"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Yee Tsai"
  job      : "Software Engineer"
  bio      : ""
  thumb    : /images/favicon.png
  email    : yee.tsai@gmail.com
  url      : http://0x01.im
  github   : http://github.com/yeetsai
  twitter  : http://twitter.com/yeesword
  facebook : https://www.facebook.com/yee.tsai.96
  linkedin : http://www.linkedin.com/in/yee-tsai-b29239b

# social settings
og_locale: "zh_CN"
twitter_card: "summary_large_image"
twitter_site: "@yeesword"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
